<script setup>
import { ref, watch } from 'vue';
import WorkflowHistory from '../../../../shared/components/WorkflowHistory.vue';
const props = defineProps({ request: { type: Function, required: true }, backendUrl: { type: Function, default: value => value }, accountId: { type: [Number, String], required: true }, expenseId: { type: [Number, String], default: 0 }, canView: { type: Boolean, default: false } });
const emit = defineEmits(['clear-expense']);
const item = ref(null); const rows = ref([]); const message = ref(''); const busy = ref(false); const kind = ref(props.canView ? 'mine' : 'review');
async function open(id) { if (!id) return; busy.value = true; message.value = ''; try { item.value = (await props.request(`/expense/detail?id=${Number(id)}`)).item; } catch (error) { message.value = error.message; } finally { busy.value = false; } }
async function load(nextKind = kind.value) { kind.value = nextKind === 'mine' && !props.canView ? 'review' : nextKind; busy.value = true; message.value = ''; try { if (props.expenseId) { await open(props.expenseId); return; } if (kind.value === 'mine') { const data = await props.request('/expense/list?page=1&page_size=100'); rows.value = data.items || []; } else { const data = await props.request(`/workflow/inbox?kind=${kind.value === 'cc' ? 'cc' : 'review'}&page=1&page_size=100`); rows.value = (data.items || []).filter(row => row.entity_type === 'base_expense'); } } catch (error) { message.value = error.message; } finally { busy.value = false; } }
watch(() => [props.accountId, props.expenseId, props.canView], () => { item.value = null; rows.value = []; kind.value = props.canView ? 'mine' : 'review'; load(); }, { immediate: true });
</script>
<template><article class="expense-approval"><h1>基地建设费用申请</h1><p v-if="message" role="status">{{ message }}</p><template v-if="!item"><nav class="expense-tabs"><button v-if="canView" type="button" :class="{ active: kind === 'mine' }" @click="load('mine')">申请列表</button><button type="button" :class="{ active: kind === 'review' }" @click="load('review')">待我审批</button><button type="button" :class="{ active: kind === 'cc' }" @click="load('cc')">抄送给我</button><button type="button" :disabled="busy" @click="load()">刷新</button></nav><p v-if="!busy && !rows.length">暂无{{ kind === 'review' ? '待审批申请' : kind === 'cc' ? '抄送记录' : '经费申请' }}。</p><button v-for="row in rows" :key="row.task_id || row.id" type="button" class="expense-row" @click="open(row.entity_id || row.id)"><strong>{{ row.snapshot_json?.expense?.title || row.title || row.name || '基地建设费用申请' }}</strong><span>{{ row.snapshot_json?.expense?.total_amount || row.total_amount || row.amount || '' }} · {{ kind === 'mine' ? row.workflow_status : `第 ${row.round} 轮` }}</span></button></template><template v-else><button type="button" @click="emit('clear-expense'); item = null">返回列表</button><p>{{ item.title || item.name }} · {{ item.total_amount || item.amount }}</p><p>学年学期：{{ item.semester || '—' }}；基地类型：{{ item.base_type || '—' }}；基地类别：{{ item.base_category || '—' }}</p><ul><li v-for="line in item.items || []" :key="line.id">{{ line.project }}：{{ line.amount }}</li></ul><WorkflowHistory :entity-type="'base_expense'" :entity-id="item.id" :account-id="accountId" :request="request" :backend-url="backendUrl" @updated="open(item.id)" /></template></article></template>
<style scoped>
.expense-approval { padding: 16px; color: var(--app-text, #253248); }
.expense-row { display: grid; gap: 5px; width: 100%; margin: 8px 0; padding: 12px; text-align: left; border: 1px solid var(--app-line, #dbe1ea); border-radius: 8px; background: #fff; color: inherit; }
.expense-row span { color: #6d798b; font-size: 12px; }
.expense-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; }
.expense-tabs .active { border-color: #3568aa; color: #245fac; background: #eef4ff; }
button { padding: 8px 12px; border: 1px solid #dbe1ea; border-radius: 5px; background: #fff; color: inherit; }
</style>
