<?php

namespace app\server\edu;

use PDO;

class EduImportSchema
{
    public static function statements(): array
    {
        return [
            "CREATE TABLE IF NOT EXISTS `edu_import_batch` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `import_type` VARCHAR(40) NOT NULL,
                `file_id` BIGINT UNSIGNED DEFAULT NULL,
                `file_sha256` CHAR(64) DEFAULT NULL,
                `academic_year` VARCHAR(40) DEFAULT NULL,
                `semester` VARCHAR(20) DEFAULT NULL,
                `scope_key` VARCHAR(180) DEFAULT NULL,
                `status` VARCHAR(40) DEFAULT 'queued',
                `progress` TINYINT UNSIGNED DEFAULT 0,
                `total_rows` INT UNSIGNED DEFAULT 0,
                `valid_rows` INT UNSIGNED DEFAULT 0,
                `invalid_rows` INT UNSIGNED DEFAULT 0,
                `created_count` INT UNSIGNED DEFAULT 0,
                `updated_count` INT UNSIGNED DEFAULT 0,
                `missing_count` INT UNSIGNED DEFAULT 0,
                `disabled_count` INT UNSIGNED DEFAULT 0,
                `failed_count` INT UNSIGNED DEFAULT 0,
                `error_message` VARCHAR(1000) DEFAULT NULL,
                `created_by` BIGINT UNSIGNED DEFAULT NULL,
                `confirmed_by` BIGINT UNSIGNED DEFAULT NULL,
                `confirmed_at` DATETIME DEFAULT NULL,
                `completed_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_batch_uuid` (`uuid`),
                KEY `idx_edu_batch_type_status` (`import_type`, `status`, `created_at`),
                KEY `idx_edu_batch_scope` (`academic_year`, `semester`, `import_type`),
                KEY `idx_edu_batch_file` (`file_sha256`),
                KEY `idx_edu_batch_scope_key` (`scope_key`, `status`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_student_source` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `source_key` VARCHAR(180) NOT NULL,
                `student_num` VARCHAR(80) NOT NULL,
                `student_name` VARCHAR(80) NOT NULL,
                `gender` VARCHAR(20) DEFAULT NULL,
                `grade_code` VARCHAR(80) DEFAULT NULL,
                `grade_name` VARCHAR(80) DEFAULT NULL,
                `dep_code` VARCHAR(80) DEFAULT NULL,
                `dep_name` VARCHAR(120) DEFAULT NULL,
                `profession_code` VARCHAR(80) DEFAULT NULL,
                `profession_name` VARCHAR(180) DEFAULT NULL,
                `class_num` VARCHAR(80) DEFAULT NULL,
                `class_name` VARCHAR(120) DEFAULT NULL,
                `student_status` VARCHAR(40) DEFAULT NULL,
                `campus_status` VARCHAR(40) DEFAULT NULL,
                `enrollment_status` VARCHAR(40) DEFAULT NULL,
                `education_level` VARCHAR(80) DEFAULT NULL,
                `training_level` VARCHAR(80) DEFAULT NULL,
                `enrollment_date` VARCHAR(40) DEFAULT NULL,
                `graduation_year` VARCHAR(40) DEFAULT NULL,
                `email` VARCHAR(120) DEFAULT NULL,
                `source_status` VARCHAR(40) DEFAULT 'active',
                `mapping_status` VARCHAR(40) DEFAULT 'pending',
                `grade_id` BIGINT UNSIGNED DEFAULT NULL,
                `dep_id` BIGINT UNSIGNED DEFAULT NULL,
                `profession_id` BIGINT UNSIGNED DEFAULT NULL,
                `class_id` BIGINT UNSIGNED DEFAULT NULL,
                `student_id` BIGINT UNSIGNED DEFAULT NULL,
                `mobile_hmac` CHAR(64) DEFAULT NULL,
                `identity_last_six_hmac` CHAR(64) DEFAULT NULL,
                `sensitive_payload_cipher` MEDIUMTEXT DEFAULT NULL,
                `raw_payload` JSON DEFAULT NULL,
                `source_hash` CHAR(64) DEFAULT NULL,
                `scope_key` VARCHAR(180) DEFAULT NULL,
                `last_seen_batch_id` BIGINT UNSIGNED DEFAULT NULL,
                `last_seen_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_student_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_student_source_key` (`source_key`),
                UNIQUE KEY `uk_edu_student_num` (`student_num`),
                KEY `idx_edu_student_scope` (`grade_code`, `dep_code`, `profession_code`, `class_num`),
                KEY `idx_edu_student_status_batch` (`source_status`, `last_seen_batch_id`),
                KEY `idx_edu_student_mobile_hash` (`mobile_hmac`),
                KEY `idx_edu_student_scope_key` (`scope_key`, `source_status`),
                KEY `idx_edu_student_mapping` (`mapping_status`, `grade_id`, `dep_id`, `profession_id`, `class_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_teaching_plan_source` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `source_key` CHAR(64) NOT NULL,
                `academic_year` VARCHAR(40) NOT NULL,
                `semester` VARCHAR(20) NOT NULL,
                `grade_code` VARCHAR(80) DEFAULT NULL,
                `grade_name` VARCHAR(80) DEFAULT NULL,
                `dep_code` VARCHAR(80) DEFAULT NULL,
                `dep_name` VARCHAR(120) DEFAULT NULL,
                `profession_code` VARCHAR(80) DEFAULT NULL,
                `profession_name` VARCHAR(180) DEFAULT NULL,
                `course_code` VARCHAR(120) DEFAULT NULL,
                `course_name` VARCHAR(180) DEFAULT NULL,
                `course_category` VARCHAR(80) DEFAULT NULL,
                `course_nature` VARCHAR(80) DEFAULT NULL,
                `credit` DECIMAL(8,2) DEFAULT NULL,
                `weekly_hours` DECIMAL(8,2) DEFAULT NULL,
                `total_hours` DECIMAL(10,2) DEFAULT NULL,
                `theory_hours` DECIMAL(10,2) DEFAULT NULL,
                `experiment_hours` DECIMAL(10,2) DEFAULT NULL,
                `practice_hours` DECIMAL(10,2) DEFAULT NULL,
                `other_hours` DECIMAL(10,2) DEFAULT NULL,
                `source_status` VARCHAR(40) DEFAULT 'active',
                `mapping_status` VARCHAR(40) DEFAULT 'pending',
                `business_type` VARCHAR(40) DEFAULT NULL,
                `candidate_status` VARCHAR(40) DEFAULT 'pending',
                `grade_id` BIGINT UNSIGNED DEFAULT NULL,
                `dep_id` BIGINT UNSIGNED DEFAULT NULL,
                `profession_id` BIGINT UNSIGNED DEFAULT NULL,
                `raw_payload` JSON DEFAULT NULL,
                `source_hash` CHAR(64) DEFAULT NULL,
                `scope_key` VARCHAR(180) DEFAULT NULL,
                `last_seen_batch_id` BIGINT UNSIGNED DEFAULT NULL,
                `last_seen_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_plan_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_plan_source_key` (`source_key`),
                KEY `idx_edu_plan_scope_status` (`academic_year`, `semester`, `source_status`),
                KEY `idx_edu_plan_mapping` (`grade_code`, `dep_code`, `profession_code`),
                KEY `idx_edu_plan_candidate` (`business_type`, `candidate_status`),
                KEY `idx_edu_plan_scope_key` (`scope_key`, `source_status`),
                KEY `idx_edu_plan_course` (`course_code`, `academic_year`, `semester`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_course_offering_source` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `source_key` VARCHAR(180) NOT NULL,
                `teaching_class_id` VARCHAR(180) NOT NULL,
                `academic_year` VARCHAR(40) NOT NULL,
                `semester` VARCHAR(20) NOT NULL,
                `course_code` VARCHAR(120) DEFAULT NULL,
                `course_name` VARCHAR(180) DEFAULT NULL,
                `open_dep_code` VARCHAR(80) DEFAULT NULL,
                `open_dep_name` VARCHAR(120) DEFAULT NULL,
                `class_composition` TEXT DEFAULT NULL,
                `teacher_numbers` TEXT DEFAULT NULL,
                `teacher_names` TEXT DEFAULT NULL,
                `teaching_type` VARCHAR(40) DEFAULT NULL,
                `course_nature` VARCHAR(80) DEFAULT NULL,
                `start_week` VARCHAR(40) DEFAULT NULL,
                `end_week` VARCHAR(40) DEFAULT NULL,
                `time_text` TEXT DEFAULT NULL,
                `location` TEXT DEFAULT NULL,
                `source_status` VARCHAR(40) DEFAULT 'active',
                `mapping_status` VARCHAR(40) DEFAULT 'pending',
                `business_type` VARCHAR(40) DEFAULT NULL,
                `candidate_status` VARCHAR(40) DEFAULT 'pending',
                `grade_code` VARCHAR(80) DEFAULT NULL,
                `dep_id` BIGINT UNSIGNED DEFAULT NULL,
                `course_id` BIGINT UNSIGNED DEFAULT NULL,
                `raw_payload` JSON DEFAULT NULL,
                `source_hash` CHAR(64) DEFAULT NULL,
                `scope_key` VARCHAR(180) DEFAULT NULL,
                `last_seen_batch_id` BIGINT UNSIGNED DEFAULT NULL,
                `last_seen_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_offering_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_offering_source_key` (`source_key`),
                UNIQUE KEY `uk_edu_offering_class_id` (`teaching_class_id`),
                KEY `idx_edu_offering_scope_status` (`academic_year`, `semester`, `source_status`),
                KEY `idx_edu_offering_course` (`course_code`, `academic_year`, `semester`),
                KEY `idx_edu_offering_candidate` (`business_type`, `candidate_status`),
                KEY `idx_edu_offering_scope_key` (`scope_key`, `source_status`),
                KEY `idx_edu_offering_seen_status` (`last_seen_batch_id`, `source_status`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_course_offering_teacher` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `offering_id` BIGINT UNSIGNED NOT NULL,
                `teacher_num` VARCHAR(80) NOT NULL,
                `teacher_id` BIGINT UNSIGNED DEFAULT NULL,
                `teacher_role` VARCHAR(40) DEFAULT NULL,
                `sort` INT DEFAULT 0,
                `status` VARCHAR(40) DEFAULT 'enabled',
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_offering_teacher_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_offering_teacher` (`offering_id`, `teacher_num`),
                KEY `idx_edu_teacher_offering` (`teacher_num`, `offering_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_course_offering_class` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `offering_id` BIGINT UNSIGNED NOT NULL,
                `class_num` VARCHAR(80) NOT NULL,
                `class_id` BIGINT UNSIGNED DEFAULT NULL,
                `sort` INT DEFAULT 0,
                `status` VARCHAR(40) DEFAULT 'enabled',
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_offering_class_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_offering_class` (`offering_id`, `class_num`),
                KEY `idx_edu_class_offering` (`class_num`, `offering_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            self::stageTable('edu_student_stage'),
            self::stageTable('edu_teaching_plan_stage'),
            self::stageTable('edu_course_offering_stage'),
            "CREATE TABLE IF NOT EXISTS `edu_import_change` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `batch_id` BIGINT UNSIGNED NOT NULL,
                `entity_type` VARCHAR(40) NOT NULL,
                `source_key` VARCHAR(180) NOT NULL,
                `change_type` VARCHAR(40) NOT NULL,
                `confirm_status` VARCHAR(40) DEFAULT 'pending',
                `before_json` JSON DEFAULT NULL,
                `after_json` JSON DEFAULT NULL,
                `diff_json` JSON DEFAULT NULL,
                `confirmed_by` BIGINT UNSIGNED DEFAULT NULL,
                `confirmed_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_change_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_change_source` (`batch_id`, `entity_type`, `source_key`),
                KEY `idx_edu_change_confirm` (`batch_id`, `change_type`, `confirm_status`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_import_issue` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `batch_id` BIGINT UNSIGNED NOT NULL,
                `row_number` INT UNSIGNED NOT NULL,
                `field_name` VARCHAR(120) DEFAULT NULL,
                `issue_type` VARCHAR(40) NOT NULL,
                `message` VARCHAR(1000) NOT NULL,
                `raw_value_masked` VARCHAR(500) DEFAULT NULL,
                `resolved` ENUM('false','true') DEFAULT 'false',
                `resolved_by` BIGINT UNSIGNED DEFAULT NULL,
                `resolved_at` DATETIME DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_issue_uuid` (`uuid`),
                KEY `idx_edu_issue_batch_row` (`batch_id`, `resolved`, `row_number`),
                KEY `idx_edu_issue_type` (`issue_type`, `resolved`, `created_at`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
            "CREATE TABLE IF NOT EXISTS `edu_business_candidate` (
                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                `uuid` CHAR(36) DEFAULT NULL,
                `name` VARCHAR(180) DEFAULT NULL,
                `code` VARCHAR(120) DEFAULT NULL,
                `source_type` VARCHAR(40) NOT NULL,
                `source_id` BIGINT UNSIGNED NOT NULL,
                `source_key` VARCHAR(180) NOT NULL,
                `business_type` VARCHAR(40) DEFAULT NULL,
                `classification_source` VARCHAR(40) DEFAULT NULL,
                `classification_reason` VARCHAR(255) DEFAULT NULL,
                `candidate_status` VARCHAR(40) DEFAULT 'pending',
                `mapping_status` VARCHAR(40) DEFAULT 'pending',
                `grade_id` BIGINT UNSIGNED DEFAULT NULL,
                `dep_id` BIGINT UNSIGNED DEFAULT NULL,
                `profession_id` BIGINT UNSIGNED DEFAULT NULL,
                `class_id` BIGINT UNSIGNED DEFAULT NULL,
                `generated_business_id` BIGINT UNSIGNED DEFAULT NULL,
                `confirmed_by` BIGINT UNSIGNED DEFAULT NULL,
                `confirmed_at` DATETIME DEFAULT NULL,
                `raw_payload` JSON DEFAULT NULL,
                `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
                `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                `deleted_at` DATETIME DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `uk_edu_candidate_uuid` (`uuid`),
                UNIQUE KEY `uk_edu_candidate_source` (`source_type`, `source_id`, `business_type`),
                KEY `idx_edu_candidate_status` (`candidate_status`, `business_type`, `created_at`),
                KEY `idx_edu_candidate_scope` (`grade_id`, `dep_id`, `profession_id`, `candidate_status`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        ];
    }

    public static function ensure(PDO $pdo): void
    {
        foreach (self::statements() as $statement) {
            $pdo->exec($statement);
        }

        foreach ([
            ['edu_student_source', 'source_key', "ALTER TABLE `edu_student_source` ADD COLUMN `source_key` VARCHAR(180) NOT NULL AFTER `code`"],
            ['edu_course_offering_source', 'source_key', "ALTER TABLE `edu_course_offering_source` ADD COLUMN `source_key` VARCHAR(180) NOT NULL AFTER `code`"],
            ['edu_student_source', 'scope_key', "ALTER TABLE `edu_student_source` ADD COLUMN `scope_key` VARCHAR(180) DEFAULT NULL AFTER `source_hash`"],
            ['edu_teaching_plan_source', 'scope_key', "ALTER TABLE `edu_teaching_plan_source` ADD COLUMN `scope_key` VARCHAR(180) DEFAULT NULL AFTER `source_hash`"],
            ['edu_course_offering_source', 'scope_key', "ALTER TABLE `edu_course_offering_source` ADD COLUMN `scope_key` VARCHAR(180) DEFAULT NULL AFTER `source_hash`"],
            ['edu_student_stage', 'change_type', "ALTER TABLE `edu_student_stage` ADD COLUMN `change_type` VARCHAR(40) DEFAULT NULL AFTER `issue_count`"],
            ['edu_teaching_plan_stage', 'change_type', "ALTER TABLE `edu_teaching_plan_stage` ADD COLUMN `change_type` VARCHAR(40) DEFAULT NULL AFTER `issue_count`"],
            ['edu_course_offering_stage', 'change_type', "ALTER TABLE `edu_course_offering_stage` ADD COLUMN `change_type` VARCHAR(40) DEFAULT NULL AFTER `issue_count`"],
            ['edu_student_stage', 'before_json', "ALTER TABLE `edu_student_stage` ADD COLUMN `before_json` JSON DEFAULT NULL AFTER `change_type`"],
            ['edu_teaching_plan_stage', 'before_json', "ALTER TABLE `edu_teaching_plan_stage` ADD COLUMN `before_json` JSON DEFAULT NULL AFTER `change_type`"],
            ['edu_course_offering_stage', 'before_json', "ALTER TABLE `edu_course_offering_stage` ADD COLUMN `before_json` JSON DEFAULT NULL AFTER `change_type`"],
            ['edu_student_stage', 'diff_json', "ALTER TABLE `edu_student_stage` ADD COLUMN `diff_json` JSON DEFAULT NULL AFTER `before_json`"],
            ['edu_teaching_plan_stage', 'diff_json', "ALTER TABLE `edu_teaching_plan_stage` ADD COLUMN `diff_json` JSON DEFAULT NULL AFTER `before_json`"],
            ['edu_course_offering_stage', 'diff_json', "ALTER TABLE `edu_course_offering_stage` ADD COLUMN `diff_json` JSON DEFAULT NULL AFTER `before_json`"],
            ['edu_student_stage', 'classification_source', "ALTER TABLE `edu_student_stage` ADD COLUMN `classification_source` VARCHAR(40) DEFAULT NULL AFTER `diff_json`"],
            ['edu_teaching_plan_stage', 'classification_source', "ALTER TABLE `edu_teaching_plan_stage` ADD COLUMN `classification_source` VARCHAR(40) DEFAULT NULL AFTER `diff_json`"],
            ['edu_course_offering_stage', 'classification_source', "ALTER TABLE `edu_course_offering_stage` ADD COLUMN `classification_source` VARCHAR(40) DEFAULT NULL AFTER `diff_json`"],
            ['edu_student_stage', 'classification_reason', "ALTER TABLE `edu_student_stage` ADD COLUMN `classification_reason` VARCHAR(255) DEFAULT NULL AFTER `classification_source`"],
            ['edu_teaching_plan_stage', 'classification_reason', "ALTER TABLE `edu_teaching_plan_stage` ADD COLUMN `classification_reason` VARCHAR(255) DEFAULT NULL AFTER `classification_source`"],
            ['edu_course_offering_stage', 'classification_reason', "ALTER TABLE `edu_course_offering_stage` ADD COLUMN `classification_reason` VARCHAR(255) DEFAULT NULL AFTER `classification_source`"],
        ] as [$table, $column, $ddl]) {
            $stmt = $pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?');
            $stmt->execute([$table, $column]);
            if (!(int) $stmt->fetchColumn()) {
                $pdo->exec($ddl);
            }
        }

        foreach ([
            ['edu_student_source', 'uk_edu_student_source_key', "ALTER TABLE `edu_student_source` ADD UNIQUE KEY `uk_edu_student_source_key` (`source_key`)"],
            ['edu_course_offering_source', 'uk_edu_offering_source_key', "ALTER TABLE `edu_course_offering_source` ADD UNIQUE KEY `uk_edu_offering_source_key` (`source_key`)"],
            ['edu_student_source', 'idx_edu_student_scope_key', "ALTER TABLE `edu_student_source` ADD KEY `idx_edu_student_scope_key` (`scope_key`, `source_status`)"],
            ['edu_teaching_plan_source', 'idx_edu_plan_scope_key', "ALTER TABLE `edu_teaching_plan_source` ADD KEY `idx_edu_plan_scope_key` (`scope_key`, `source_status`)"],
            ['edu_course_offering_source', 'idx_edu_offering_scope_key', "ALTER TABLE `edu_course_offering_source` ADD KEY `idx_edu_offering_scope_key` (`scope_key`, `source_status`)"],
        ] as [$table, $index, $ddl]) {
            $stmt = $pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND INDEX_NAME = ?');
            $stmt->execute([$table, $index]);
            if (!(int) $stmt->fetchColumn()) {
                $pdo->exec($ddl);
            }
        }
    }

    private static function stageTable(string $table): string
    {
        return "CREATE TABLE IF NOT EXISTS `{$table}` (
            `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            `uuid` CHAR(36) DEFAULT NULL,
            `name` VARCHAR(180) DEFAULT NULL,
            `code` VARCHAR(120) DEFAULT NULL,
            `batch_id` BIGINT UNSIGNED NOT NULL,
            `source_key` VARCHAR(180) NOT NULL,
            `row_number` INT UNSIGNED NOT NULL,
            `source_hash` CHAR(64) DEFAULT NULL,
            `normalized_payload` JSON DEFAULT NULL,
            `raw_payload` JSON DEFAULT NULL,
            `issue_count` INT UNSIGNED DEFAULT 0,
            `change_type` VARCHAR(40) DEFAULT NULL,
            `before_json` JSON DEFAULT NULL,
            `diff_json` JSON DEFAULT NULL,
            `classification_source` VARCHAR(40) DEFAULT NULL,
            `classification_reason` VARCHAR(255) DEFAULT NULL,
            `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
            `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            `deleted_at` DATETIME DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `uk_{$table}_uuid` (`uuid`),
            UNIQUE KEY `uk_{$table}_source` (`batch_id`, `source_key`),
            KEY `idx_{$table}_batch_row` (`batch_id`, `row_number`),
            KEY `idx_{$table}_batch_issue` (`batch_id`, `issue_count`),
            KEY `idx_{$table}_batch_change` (`batch_id`, `change_type`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4";
    }
}
