CREATE TABLE IF NOT EXISTS `data_cleanup_task` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) DEFAULT NULL,
    `name` VARCHAR(180) DEFAULT NULL,
    `code` VARCHAR(120) DEFAULT NULL,
    `status` VARCHAR(40) DEFAULT 'queued',
    `created_by` BIGINT UNSIGNED DEFAULT NULL,
    `scope_json` JSON DEFAULT NULL,
    `preserve_edu_data` ENUM('false','true') DEFAULT 'true',
    `progress` TINYINT UNSIGNED DEFAULT 0,
    `total_rows` BIGINT UNSIGNED DEFAULT 0,
    `affected_rows` BIGINT UNSIGNED DEFAULT 0,
    `affected_json` JSON DEFAULT NULL,
    `error_message` VARCHAR(1000) DEFAULT NULL,
    `started_at` DATETIME DEFAULT NULL,
    `finished_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cleanup_uuid` (`uuid`),
    KEY `idx_cleanup_status` (`status`, `created_at`),
    KEY `idx_cleanup_creator` (`created_by`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
