CREATE TABLE IF NOT EXISTS `base_visit_plan` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
    `revision` INT UNSIGNED NOT NULL DEFAULT 1,
    `title` VARCHAR(180) NOT NULL,
    `base_id` BIGINT UNSIGNED NOT NULL,
    `teacher_id` BIGINT UNSIGNED NOT NULL,
    `dep_id` BIGINT UNSIGNED NOT NULL,
    `base_name` VARCHAR(180) NOT NULL,
    `base_address` VARCHAR(500) DEFAULT NULL,
    `base_department` VARCHAR(180) DEFAULT NULL,
    `base_category` VARCHAR(80) DEFAULT NULL,
    `base_location` VARCHAR(40) DEFAULT NULL,
    `teacher_name` VARCHAR(120) NOT NULL,
    `teacher_department` VARCHAR(180) DEFAULT NULL,
    `contact_phone` VARCHAR(40) DEFAULT NULL,
    `visit_date` DATE DEFAULT NULL,
    `visit_period` VARCHAR(10) DEFAULT NULL,
    `start_time` TIME DEFAULT NULL,
    `end_time` TIME DEFAULT NULL,
    `remark` TEXT DEFAULT NULL,
    `status` VARCHAR(40) NOT NULL DEFAULT 'pending_time',
    `scheduled_at` DATETIME DEFAULT NULL,
    `cancel_reason` VARCHAR(1000) DEFAULT NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_by` BIGINT UNSIGNED NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_visit_plan_uuid` (`uuid`),
    KEY `idx_visit_teacher_status_date` (`teacher_id`, `status`, `visit_date`),
    KEY `idx_visit_dep_status_date` (`dep_id`, `status`, `visit_date`),
    KEY `idx_visit_date_period_status` (`visit_date`, `visit_period`, `status`),
    KEY `idx_visit_base` (`base_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `base_visit_record` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
    `visit_id` BIGINT UNSIGNED NOT NULL,
    `actual_at` DATETIME NOT NULL,
    `participants` VARCHAR(500) DEFAULT NULL,
    `contact_person` VARCHAR(180) DEFAULT NULL,
    `content` MEDIUMTEXT NOT NULL,
    `problems` TEXT DEFAULT NULL,
    `follow_up` TEXT DEFAULT NULL,
    `attachment_ids` JSON DEFAULT NULL,
    `created_by` BIGINT UNSIGNED NOT NULL,
    `updated_by` BIGINT UNSIGNED NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_visit_record_uuid` (`uuid`),
    UNIQUE KEY `uk_visit_record_plan` (`visit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
