CREATE TABLE IF NOT EXISTS `account_import_task` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `uuid` CHAR(36) NOT NULL,
    `request_key` VARCHAR(64) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'queued',
    `created_by` BIGINT UNSIGNED NOT NULL,
    `file_id` BIGINT UNSIGNED DEFAULT NULL,
    `source_json` JSON DEFAULT NULL,
    `password_hash` VARCHAR(255) DEFAULT NULL,
    `total_rows` INT UNSIGNED NOT NULL DEFAULT 0,
    `processed_rows` INT UNSIGNED NOT NULL DEFAULT 0,
    `created_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `linked_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `updated_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `skipped_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `failed_count` INT UNSIGNED NOT NULL DEFAULT 0,
    `errors_json` JSON DEFAULT NULL,
    `error_message` VARCHAR(500) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `finished_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_account_import_uuid` (`uuid`),
    UNIQUE KEY `uk_account_import_request` (`created_by`, `request_key`),
    KEY `idx_account_import_owner` (`created_by`, `type`, `id`),
    KEY `idx_account_import_status` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
